version: 2
jobs:
  build:
    machine: true
    environment:
      JAVA_TOOL_OPTIONS: "-Xms300m -Xmx400m"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx300m -Xmx400m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
      TERM: dumb
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run:
          name: "Running build"
          command: ./scripts/runAcceptanceTests.sh
